name: "{GitHub username}'s Action in Action."
description: "Greets someon and returns 42"
inputs:
  who-to-greet:
    description: "who to greet"
    required: true
    default: 'Bahram'
outputs:
  answer:
    description: 'The answer to everything'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}